create table if not exists public.investor_signups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  signup_type text not null check (signup_type in ('managed_service', 'solar_bond_waitlist')),
  email text not null,
  full_name text,
  organization text,
  geographic_area text,
  investment_preference text check (investment_preference in ('individual_projects', 'solar_bond', 'both')),
  ticket_size text,
  notes text
);

create index if not exists investor_signups_email_idx on public.investor_signups (email);
create index if not exists investor_signups_signup_type_idx on public.investor_signups (signup_type);
